### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by senrabc** [lawlesst/vivo-rdflib-sparqlstore#1]
Trying this on the vagrant. Curl works, vivoUpdate throws error. curl and vivoUpdate output below

 $  curl -i -d 'email=vivo_root@school.edu' -d 'password=xxxx' -d 'query=DESCRIBE http://dbpedia.org/resource/Florida' -H 'Accept: text/n3' 'http://localhost:8080/vivo/api/sparqlQuery'
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=A503F55E0CC30AECCB348BDC24A40372; Path=/vivo/; HttpOnly
X-FRAME-OPTIONS: SAMEORIGIN
Content-Type: text/n3;charset=UTF-8
Content-Length: 6853
Date: Fri, 01 Apr 2016 14:17:10 GMT

@prefix p3:    http://vivoweb.org/ontology/provenance-support# .
@prefix scires: http://vivoweb.org/ontology/scientific-research# .
@prefix p2:    http://purl.org/dc/terms/ .
@prefix cito:  http://purl.org/spar/cito/ .
@prefix p1:    http://purl.org/dc/elements/1.1/ .
@prefix dcterms: http://purl.org/dc/terms/ .
@prefix rdfs:  http://www.w3.org/2000/01/rdf-schema# .
@prefix swrl:  http://www.w3.org/2003/11/swrl# .
@prefix vitro: http://vitro.mannlib.cornell.edu/ns/vitro/public# .
@prefix event: http://purl.org/NET/c4dm/event.owl# .
@prefix c4o:   http://purl.org/spar/c4o/ .
@prefix rdf:   http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix vivo:  http://vivoweb.org/ontology/core# .
@prefix dcelem: http://purl.org/dc/elements/1.1/ .
@prefix ocresd: http://purl.org/net/OCRe/study_design.owl# .
@prefix vitro1: http://vitro.mannlib.cornell.edu/ns/vitro/0.7# .
@prefix pvs:   http://vivoweb.org/ontology/provenance-support# .
@prefix geo:   http://aims.fao.org/aos/geopolitical.owl# .
@prefix vitro2: http://vitro.mannlib.cornell.edu/ns/vitro/public# .
@prefix foaf:  http://xmlns.com/foaf/0.1/ .
@prefix j.1:   http://xmlns.com/foaf/0.1/ .
@prefix j.0:   http://vitro.mannlib.cornell.edu/ns/vitro/0.7# .
@prefix fabio: http://purl.org/spar/fabio/ .
@prefix j.3:   http://vivoweb.org/ontology/core# .
@prefix j.2:   http://vivoweb.org/ontology/core# .
@prefix vcard: http://www.w3.org/2006/vcard/ns# .
@prefix obo:   http://purl.obolibrary.org/obo/ .
@prefix ocrer: http://purl.org/net/OCRe/research.owl# .
@prefix j.4:   http://vivoweb.org/ontology/core# .
@prefix j.5:   http://vitro.mannlib.cornell.edu/ns/vitro/0.7# .
@prefix bibo:  http://purl.org/ontology/bibo/ .
@prefix owl:   http://www.w3.org/2002/07/owl# .
@prefix swrlb: http://www.w3.org/2003/11/swrlb# .
@prefix xsd:   http://www.w3.org/2001/XMLSchema# .
@prefix core:  http://vivoweb.org/ontology/core# .
@prefix skos:  http://www.w3.org/2004/02/skos/core# .
@prefix ero:   http://purl.obolibrary.org/obo/ .
@prefix ufVivo: http://vivo.ufl.edu/ontology/vivo-ufl/ .

http://dbpedia.org/resource/Florida
        a                       owl:Thing , ero:BFO_0000006 , core:Location , core:GeographicRegion , ero:BFO_0000004 , ero:BFO_0000001 , ero:BFO_0000141 , core:GeographicLocation , ero:BFO_0000002 , core:GeopoliticalEntity , core:StateOrProvince ;
        rdfs:label              "Florida"@en ;
        ero:BFO_0000050         geo:United_States_of_America ;
        ero:BFO_0000051         http://vivo.ufl.edu/individual/n33431 , http://vivo.ufl.edu/individual/n56413 , http://vivo.ufl.edu/individual/n68089 , http://vivo.ufl.edu/individual/n56961 , http://vivo.ufl.edu/individual/n126969 , http://vivo.ufl.edu/individual/n117881 , http://vivo.ufl.edu/individual/n4753957995 , http://vivo.ufl.edu/individual/n121898 , http://vivo.ufl.edu/individual/n72547 , http://vivo.ufl.edu/individual/n127962 , http://vivo.ufl.edu/individual/n52606 , http://vivo.ufl.edu/individual/n189222 , http://vivo.ufl.edu/individual/n2837484846 , http://vivo.ufl.edu/individual/n111180 , http://vivo.ufl.edu/individual/n102341 , http://vivo.ufl.edu/individual/n97136 , http://vivo.ufl.edu/individual/n5788401625 , http://vivo.ufl.edu/individual/n33213 , http://vivo.ufl.edu/individual/n121372 , http://vivo.ufl.edu/individual/n63147 , http://vivo.ufl.edu/individual/n67989 , http://vivo.ufl.edu/individual/n53936 , http://vivo.ufl.edu/individual/n9578362660 , http://vivo.ufl.edu/individual/n232328 , http://vivo.ufl.edu/individual/n234433 , http://vivo.ufl.edu/individual/n118878 , http://vivo.ufl.edu/individual/n112043 , http://vivo.ufl.edu/individual/n222951 , http://vivo.ufl.edu/individual/n195839 , http://vivo.ufl.edu/individual/n86029 , http://vivo.ufl.edu/individual/n95478 , http://vivo.ufl.edu/individual/n5968520187 , http://vivo.ufl.edu/individual/n54265 , http://vivo.ufl.edu/individual/n170197 , http://vivo.ufl.edu/individual/n152754 , http://vivo.ufl.edu/individual/n86346 , http://vivo.ufl.edu/individual/n38823 , http://vivo.ufl.edu/individual/n26382 , http://vivo.ufl.edu/individual/n176306 , http://vivo.ufl.edu/individual/n101256 , http://vivo.ufl.edu/individual/n45302 , http://vivo.ufl.edu/individual/n55005 , http://vivo.ufl.edu/individual/n17082 , http://vivo.ufl.edu/individual/n4947492015 , http://vivo.ufl.edu/individual/n37720 , http://vivo.ufl.edu/individual/n202354 , http://vivo.ufl.edu/individual/n78965 , http://vivo.ufl.edu/individual/n81644 , http://vivo.ufl.edu/individual/n36212 , http://vivo.ufl.edu/individual/n91093 , http://vivo.ufl.edu/individual/n65162 , http://vivo.ufl.edu/individual/n121951 , http://vivo.ufl.edu/individual/n60774 , http://vivo.ufl.edu/individual/n56367 , http://vivo.ufl.edu/individual/n45881 , http://vivo.ufl.edu/individual/n62024 , http://vivo.ufl.edu/individual/n218921 , http://vivo.ufl.edu/individual/n23519 , http://vivo.ufl.edu/individual/n118230 , http://vivo.ufl.edu/individual/n4726377078 , http://vivo.ufl.edu/individual/n24618 , http://vivo.ufl.edu/individual/n46554 , http://vivo.ufl.edu/individual/n121330 , http://vivo.ufl.edu/individual/n26205 , http://vivo.ufl.edu/individual/n58506 , http://vivo.ufl.edu/individual/n167222 , http://vivo.ufl.edu/individual/n88615 , http://vivo.ufl.edu/individual/n9455103844 , http://vivo.ufl.edu/individual/n5462057093 , http://vivo.ufl.edu/individual/n114000 , http://vivo.ufl.edu/individual/n41072 , http://vivo.ufl.edu/individual/n249227 , http://vivo.ufl.edu/individual/n403125 , http://vivo.ufl.edu/individual/n336629 , http://vivo.ufl.edu/individual/n3692105755 , http://vivo.ufl.edu/individual/n91991 , http://vivo.ufl.edu/individual/n64645 , http://vivo.ufl.edu/individual/n80968 , http://vivo.ufl.edu/individual/n1323016223 , http://vivo.ufl.edu/individual/n83894 , http://vivo.ufl.edu/individual/n125931 , http://vivo.ufl.edu/individual/n31620 , http://vivo.ufl.edu/individual/n90671 , http://vivo.ufl.edu/individual/n8561274649 , http://vivo.ufl.edu/individual/n157503 , http://vivo.ufl.edu/individual/n106225 , http://vivo.ufl.edu/individual/n360598 , http://vivo.ufl.edu/individual/n115297 , http://vivo.ufl.edu/individual/n56069 , http://vivo.ufl.edu/individual/n74064 , http://vivo.ufl.edu/individual/n4476897325 , http://vivo.ufl.edu/individual/n174286 , http://vivo.ufl.edu/individual/n78840 , http://vivo.ufl.edu/individual/n59596 ;
        j.5:mostSpecificType    core:StateOrProvince ;
        core:geographicFocusOf  http://vivo.ufl.edu/individual/n59781 , http://vivo.ufl.edu/individual/n12576 , http://vivo.ufl.edu/individual/n2010595960 , http://vivo.ufl.edu/individual/n387583 .
$ vivoUpdate --email vivo_root@school.edu --password xxxx --url 127.0.0.1:8080/vivo all_triples_harvested_test.txt remove

---

VIVO url: 127.0.0.1:8080/vivo
Traceback (most recent call last):
  File "/usr/local/bin/vivoUpdate", line 9, in <module>
    load_entry_point('vivo-rdflib-sparqlstore==0.0.1', 'console_scripts', 'vivoUpdate')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/scripts/command.py", line 52, in process
    graph.parse(source=triple_file, format=fmt)
  File "/usr/local/lib/python2.7/site-packages/rdflib/graph.py", line 1037, in parse
    parser.parse(source, self, *_args)
  File "/usr/local/lib/python2.7/site-packages/rdflib/plugins/parsers/rdfxml.py", line 577, in parse
    self._parser.parse(source)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: file:///Users/cpb/code/ctsit-forge.ctsi.ufl.edu/uf_vivo_vagrant/work/triples_to_remove/all_triples_harvested_test.txt:1:6: not well-formed (invalid token)

**Comment by lawlesst** [comment]
Try changing your file extension to ".n3". 

The code is using RDFLib's [guess_format](http://rdflib.readthedocs.org/en/stable/apidocs/rdflib.html#rdflib.util.guess_format) utility and it relies on file extensions to determine the serialization.
